package co.edu.udistrital.mdp.pets.entities;

import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import uk.co.jemos.podam.common.PodamExclude;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

@Data
@Entity
@EqualsAndHashCode(callSuper = true)
public class ShelterEventEntity extends BaseEntity {

    private String title;
    private String description;
    private String location;

    @Temporal(TemporalType.DATE)
    private Date date;

    // Belongs to a Shelter
    @PodamExclude
	@ManyToOne
    @JoinColumn(name = "shelter_id")
    private ShelterEntity shelter;

    // Relation 1:N with Report (Reports generated by this event)
    @PodamExclude
    @OneToMany
	@JoinColumn(name = "event_id")
    private List<ReportEntity> reports = new ArrayList<>();
}
